name: Deploy to Hostinger
on:
  push:
    branches:
      - main  # Ganti 'main' jika branch utama Anda namanya berbeda (misal 'master')

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/public_html/dev
            git pull origin main
            php artisan optimize:clear
